### ISSUE TITLE
Running on Github Actions

### ISSUE THREAD

**Issue by myselfhimself** [douglaskastle/blender-addon-tester#1]
Hello,
I am planning to try to use your work for https://github.com/myselfhimself/gmic-blender though I will not use Travis CI but the Github Actions instead.
I was wondering how to enable an add-on from outside Blender programmatically. It seems your [SetupPlugin() class](https://github.com/douglaskastle/blender-fake-addon/blob/651bd999419298964bd0f79f540764cae52d8939/scripts/load_pytest.py#L15) does the work... I will see in <1 month.
I do plan to use pytest as well.
Thanks for contributing your work online.
Let us keep in touch.

**Comment by myselfhimself** [comment]
Issues migrated by you thank you. I am glad of the new project created. Will open an Issue on making a pypi.org package so that at some time we do not have to target a github URL/branch anymore.
Thank you for the Windows debugging and sorry for the badly assumed `--upgrade` flag rootcause. I must say that I am not really fan of debugging Windows more than you have done so far, as long as the whole jobs end up positively.. Resilient Windows error noise are OK for me. 
As to Windows work, I will have to debug Windows C++ Python compilation on a G'MIC Python binding project soon after I have my head free with blender-addon-tester.
I am very lazy in local testing and run only Linux tests locally, counting on Github Actions to run for other OSes and Blender version combinations.
Feel free to close this issue, maybe when the Mac OS X support is landed in https://github.com/douglaskastle/blender-addon-tester/issues/2 (hopefully for wednesday latest) and when you feel satisfied with Windows support either in Github Actions and/or your travis CI setup.

**Comment by douglaskastle** [comment]
I have opened a separate issue to capture the windows local solution.

https://github.com/douglaskastle/blender-addon-tester/issues/9

The Mac OS X has it's own issue.

PyPi has it's own issue.

Happy to and am closing this issue.

Please raise any issues as you find them.
