### ISSUE TITLE
Fix blender 2.79x on linux on github actions

### ISSUE THREAD

**Issue by myselfhimself** [douglaskastle/blender-addon-tester#14]
Related to https://github.com/douglaskastle/blender-addon-tester/issues/2#issuecomment-604167199

**Comment by douglaskastle** [comment]
Ah yes, the apt get solution was in the Travis flow. It would need to be explicit here too.

Though I thought I had this writing already for 2.79...

**Comment by myselfhimself** [comment]
Fixed in Github Actions now with a linux x 2.79* only conditional, preventing side-effects for other versions or OSes :
https://github.com/douglaskastle/blender-addon-tester/runs/536903099?check_suite_focus=true
OK to close this issue?

**Comment by myselfhimself** [comment]
The related commits are on the macosx-support branch which will be mergeable into master pretty soon.

**Comment by douglaskastle** [comment]
I did have it, probably got trimmed away if you didnt know why it was there

https://github.com/douglaskastle/blender-fake-addon/blob/master/.github/workflows/pythonpackage.yml

**Comment by douglaskastle** [comment]
> Fixed in Github Actions now with a linux x 2.79* only conditional, preventing side-effects for other versions or OSes :
> https://github.com/douglaskastle/blender-addon-tester/runs/536903099?check_suite_focus=true
> OK to close this issue?

Sure, if you're happy

**Comment by myselfhimself** [comment]
> I did have it, probably got trimmed away if you didnt know why it was there
> 
> https://github.com/douglaskastle/blender-fake-addon/blob/master/.github/workflows/pythonpackage.yml

Seen. Thanks. Closing
