### ISSUE TITLE
Add support for MacOS X

### ISSUE THREAD

**Issue by myselfhimself** [douglaskastle/blender-addon-tester#2]
We need this for gmic-py x blender :)

Failing build at: https://github.com/myselfhimself/gmic-blender/runs/513968946?check_suite_focus=true

`    raise Exception(f"dmg Unsupported")`

**Comment by myselfhimself** [comment]
Continuing work on this today

**Comment by myselfhimself** [comment]
[dmglib seems to be a nice little python library to abstract dmg mounting and demounting, trying it out](https://github.com/0xbf00/dmglib)

**Comment by douglaskastle** [comment]
@myselfhimself how do I contact you outside of issues? 

my email address is douglas.kastle gmail com

**Comment by myselfhimself** [comment]
My PR was merged too early, but I now have comitter access to the repository.
Look I will just work in a branch and delete my fork.
NP
:)

**Comment by myselfhimself** [comment]
WIP branch is: https://github.com/douglaskastle/blender-addon-tester/tree/macosx-support

**Comment by myselfhimself** [comment]
Using [dmglib](https://pypi.org/project/dmglib/) was fruitful, preventing my needing to work with subprocesses.

I am struggling with the case of Blender 2.78c x mac os x. Back in the 2.78c days, packaging was obviously not done as a `dmg` but a zipped archive of a `blender.app` image folder (not Blender.app), with a lowercase blender executable in it (instead of uppercase).
Hoping to fix this today. The code of getBlender is now starting to get messy with special cases.. OOP could help at some point after this..

**Comment by myselfhimself** [comment]
Github Actions shows flakiness for environment variables management or maybe is it our project.
When running a 2.80 test alongside a 2.78c test, the 2.78c test switches from 2.78c to 2.80 in the middle and downloads blender 2.80.
Still troubleshooting that.

**Comment by douglaskastle** [comment]
Check the files in the example/* directory, I edited one to pass version and addon
 I think there are 2 others that need the same edit. 

This is where having a local machine is invaluable, and the reason I didn't develop it. Time vampire is the phrase I have heard.

**Comment by myselfhimself** [comment]
The 2.80 sticky variable issue was due to the [rebuild_pipreinstall_and_testexamples.sh](https://github.com/douglaskastle/blender-addon-tester/blob/macosx-support/rebuild_pipreinstall_and_testexamples.sh) entry point not having the BLENDER_VERSION environment variable injected (I had forgotten it).
Also each test was run one time too many.
This is now solved.

Also, Blender Mac OS X releases in the 2.78c-like older zipped format (not dmg) needed a `chmod +x` on top of the bundled blender and python executables. This is now applied.

Now I am facing an issue of blender 2.78c's bundled Python not seeing pytest.
This can be seen in [this Github Actions run](https://github.com/douglaskastle/blender-addon-tester/runs/534303022).
Highlighting the suspecting log lines:
```
2020-03-25T18:18:18.8704570Z found bundled python: /Users/runner/runners/2.165.2/work/blender-addon-tester/blender-addon-tester/.blender_releases_cache/blender-2.78c/MacOS/../Resources/2.78/python
2020-03-25T18:18:18.8768200Z Running /Users/runner/runners/2.165.2/work/blender-addon-tester/blender-addon-tester/examples/testing-fake-addon/blender_advanced_load_pytest.py from Blender
2020-03-25T18:18:18.8768900Z No module named 'pytest'
2020-03-25T18:18:18.8979570Z Error: Not freed memory blocks: 1, total unfreed memory 0.000122 MB
```
Most probably, blender's python version is not the same as the OS's python or is too different from it. So possibly package directories are not shared or acknowledged the same way. Hence, sharing the location of a non-same-python-executable version of pytest inside the python path of Blender's bundled python might not help. I do not know what to do: enforce a lower python version for when macosx X blender 2.78c is run? pip install from inside blender, which would need adding pip there? @douglaskastle  This is related to the trickery you have used and makes this project neat. Would you have some resolution idea?

**Comment by douglaskastle** [comment]
First are you sure you are picking up the blender python and not the system python? I can't tell from your log which you are using. In linux I would use readlink -f python to give me the full path.  If you are using the right python ...

2.78c was only put in to have an option.  I am now beginning to find it causing problems elsewhere, and since then 2.80, 2,81, 2,82 have come along and they provide options there weren't available when I started.

One of the problems I had, which may or may not be the problem, is that the current version of zipp, which is used by pytest, has deprecated support for 3.5.  Look over in lwo import project, i had to have a special requirements file for 2.78c.  I think he might have unrolled that change, because your work under ubuntu and windows on github works and there is no special requirements file for them.

Ultimately I think it is ok to remove 2.78c from the github actions flow.  I would like to know whats wrong, but unless you have a hard requirement for support, it not worth chasing too hard.  

I would love to get off 2.79, as this is the last using python3.5.  There are certain language constructs on 3.7 that i would like to upgrade to. But 2,79 will be a magic build for a few years to come.

Operationally there are a lot of users stuck on 2.79 who are afraid of 2.80.  I would be surprised to find anyone stuck on 2,78.  If they are not on 2.79, then they are probably on some much older version of blender, 2.65 or something, which we are not supporting any way.

**Comment by douglaskastle** [comment]
on review, i don't think you are using the blender python, just the system.  You will probably also have a problem with 2.79.  This is where the local install would be very helpful

**Comment by myselfhimself** [comment]
Hello
I have changed the mechanism of custom test script evaluation by blender's bundled python. 

Regarding these log lines:
```
2020-03-25T18:18:18.8704570Z found bundled python: /Users/runner/runners/2.165.2/work/blender-addon-tester/blender-addon-tester/.blender_releases_cache/blender-2.78c/MacOS/../Resources/2.78/python
2020-03-25T18:18:18.8768200Z Running /Users/runner/runners/2.165.2/work/blender-addon-tester/blender-addon-tester/examples/testing-fake-addon/blender_advanced_load_pytest.py from Blender
2020-03-25T18:18:18.8768900Z No module named 'pytest'
2020-03-25T18:18:18.8979570Z Error: Not freed memory blocks: 1, total unfreed memory 0.000122 MB
```
they stem from the [blender-evaluated python file](https://github.com/douglaskastle/blender-addon-tester/blob/771fae8bac2323f1b3ae6dde7f345969274802d1/examples/testing-fake-addon/blender_advanced_load_pytest.py)

which is [injected from the config dict here](https://github.com/douglaskastle/blender-addon-tester/blob/771fae8bac2323f1b3ae6dde7f345969274802d1/examples/testing-fake-addon/test_fake_addon_blender_advanced.py#L13).

Good point about blender 2.78c. Putting Blender 2.79 instead.

**Comment by myselfhimself** [comment]
Blender 2.79's download fails, it seems that scraper cannot find the download anymore on the webpage:
https://github.com/douglaskastle/blender-addon-tester/runs/534524536?check_suite_focus=true

**Comment by douglaskastle** [comment]
ok yes that look like you are calling the blender python

where is the pip install requirements happening, the failure complaint will be there by pytest is not present

**Comment by douglaskastle** [comment]
> Blender 2.79's download fails, it seems that scraper cannot find the download anymore on the webpage:
> https://github.com/douglaskastle/blender-addon-tester/runs/534524536?check_suite_focus=true

There is always something like that, I think they have issues over on blender.org today 

https://www.blendernation.com/2020/03/25/blender-org-server-issues/

**Comment by douglaskastle** [comment]
oh, make sure you do a failure test at some point.  Change the rev in the test to be wrong and make sure all the passing tests fail.  Propagating the failure out of python, to blender, to travis was lengthy enough. There is a series of tests possible around those failure modes. (also if pytest fails, it needs to error as this failure happens before blender is even called)

**Comment by douglaskastle** [comment]
also, there are failures sometimes due to source server problems, a sleep and retry should be implemented, actually that is its own issue

**Comment by myselfhimself** [comment]
The lack of match is due to blender 2.79 not existing anymore as a .zip or .dmg, just as .tar.gz
Now only blender 2.79a and 2.79b exist as zip or dmg
Related downloads list page is here: https://download.blender.org/release/Blender2.79/

**Comment by myselfhimself** [comment]
tar.gz support for macos archive added

**Comment by myselfhimself** [comment]
The MacOS archives inner files layout vary too much, this is very painful to code..:
- .tar.gz (extract)
- .dmg (to mount)
- .zip (extract)
Inside there can be a parent directory like Blender or blender-NNnNN (same name as the archive)
Then the blender.app directory can have an upper case first Blender.app
The blender executable is at blender.app/Contents/MacOS/blender
Then the python executable is python with or without numbers with m suffix or not
All executables must have +x permission added (I added x for owner, group, others for now)
In order to work once the archive is mounted or extracted, one must find the Contents directory and move to the cache dir or working directory outside any read-only macos mounting space. Then that Contents directory can be renamed to a cacheable name eg. blender-2.79b.
With macos at hand to work, in case of troubleshooting mountable dmgs on Github Actions... the easiest after a dmglib mount to os.walk or something similar into the archive and look at its contents in the logs.
MacOS blender 2.7x python executable tends to use pip 9.0.1, which has TLS issues and cannot fetch pytest from pypi.org for example, so tests will not even start. The fix is to install pip by hand [as was done for Windows already (Doug, thanks for that golden piece of code!!) here.](https://github.com/douglaskastle/blender-addon-tester/blob/0438791b9a110f9e9657c5bf019ecb2cfc04309b/blender_addon_tester/get_blender.py#L231)
This was very tedious!! Maybe in the future, blender's macos releases files layout could be uniformized.. we should report that blender.org if we want a solid blender package manager some day.

**Comment by myselfhimself** [comment]
Linux and blender 2.79b do not get on well together:
`2020-03-26T00:51:00.1362624Z /home/runner/work/blender-addon-tester/blender-addon-tester/.blender_releases_cache/blender-2.79b/blender: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory`
https://github.com/douglaskastle/blender-addon-tester/runs/535156496?check_suite_focus=true

[linux and 2.78c as well (bundled python permissions)](https://github.com/douglaskastle/blender-addon-tester/actions/runs/63428154)

**Comment by myselfhimself** [comment]
Nightlies have new compression formats:
```
2020-03-26T01:00:08.5386735Z Downloading https://builder.blender.org/download/blender-2.83-188ccfb0dd67-linux64.tar.xz
2020-03-26T01:00:08.5387157Z Error, unknown archive extension: {blender_zipfile}. Will not extract it.}
```

**Comment by myselfhimself** [comment]
tar.xz support added
It seems we are now all green for all OSes, all pytest cases, all blender >=2.80 versions including nightlies, on both [Travis CI](https://travis-ci.org/github/douglaskastle/blender-addon-tester) and [github actions](https://github.com/douglaskastle/blender-addon-tester/actions/runs/63437619)

**Comment by douglaskastle** [comment]
> Linux and blender 2.79b do not get on well together:
> `2020-03-26T00:51:00.1362624Z /home/runner/work/blender-addon-tester/blender-addon-tester/.blender_releases_cache/blender-2.79b/blender: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory`
> https://github.com/douglaskastle/blender-addon-tester/runs/535156496?check_suite_focus=true
> 
> [linux and 2.78c as well (bundled python permissions)](https://github.com/douglaskastle/blender-addon-tester/actions/runs/63428154)

I had this problem on Linux too. To get around it I did an apt-get of blender, this installed blender and all its dependacies, which are what's missing. 

I have no macosx experience, I don't know if there is a apt equivalent. 

I would recommend getting 2.79 support, as this is a massive inflection point, there will be a group of people stuck on it for years. 

However, that's up to you if you want to complete, if not, I'll take it over and try and get out working. 

I would still try and keep 2.79 operational for windows and Linux and have a pass for macosx. 

Thoughts?

**Comment by myselfhimself** [comment]
for clarification
[2.78 and 2.79 do work on mac os x as shown here](https://github.com/douglaskastle/blender-addon-tester/actions/runs/63426104)

I will try to add your 2.79 technique for linux only. For 2.78 I do not know yet.
Thanks

**Comment by douglaskastle** [comment]
yes remove 2.78, thats fine

**Comment by myselfhimself** [comment]
Good for me
