### ISSUE TITLE
Delete the blender-addon-tester branch?

### ISSUE THREAD

**Issue by myselfhimself** [douglaskastle/blender-addon-tester#6]
That branch shall not be needed anymore :)

**Comment by douglaskastle** [comment]
Correct, for this repo I am happy to work out of master until we got something working with pipy.  After that any future work will be developed on a different branch, typically for me that is develop

**Comment by douglaskastle** [comment]
Oh BTW I  struggling to see how one deletes a branch on github. I am not sure you can do it unless you are using enterprise.

**Comment by douglaskastle** [comment]
Found out how to do it, it's gone!

```
blender-addon-tester
Deleted just now by douglaskastle
```
